<?php

namespace App\Infrastructure\Persistence;

use App\Entity\Device;
use App\Entity\DeviceEvent;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Uid\Uuid;

class RawDeviceEventRecorder
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * Records a raw device event durably.
     *
     * @param string $sourceType The source identifier (e.g., essl, plc, scanner1, scanner2)
     * @param array $payload The original JSON payload as an array
     * @param string|null $sourceIp The IP of the source if available
     * @param Device|null $device The resolved device entity if known
     * @param \DateTimeImmutable|null $deviceTimestamp Timestamp supplied by the device
     * @return DeviceEvent The recorded event entity
     */
    public function recordEvent(
        string $sourceType,
        array $payload,
        ?string $sourceIp = null,
        ?Device $device = null,
        ?\DateTimeImmutable $deviceTimestamp = null
    ): DeviceEvent {
        $event = new DeviceEvent();
        
        // Generate UUID
        $event->setEventUuid(Uuid::v4()->toRfc4122());
        
        // Set metadata
        $event->setSourceType($sourceType);
        $event->setSourceIp($sourceIp);
        $event->setDevice($device);
        $event->setDeviceTimestamp($deviceTimestamp);
        
        // Microsecond precision receive timestamp is generated by default in constructor, 
        // but we can ensure it here.
        $event->setReceivedAt(new \DateTimeImmutable());
        
        // Hash and store payload
        $event->setRawPayload($payload);
        
        // Sort keys recursively for consistent hashing, encode without pretty print
        $this->recursiveKsort($payload);
        $jsonString = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        $event->setPayloadHash(hash('sha256', $jsonString));
        
        // Processing status defaults to 'received', attempts to 0

        // Persist using transaction
        $this->entityManager->wrapInTransaction(function () use ($event) {
            $this->entityManager->persist($event);
            $this->entityManager->flush();
        });

        return $event;
    }

    private function recursiveKsort(array &$array): void
    {
        ksort($array);
        foreach ($array as &$value) {
            if (is_array($value)) {
                $this->recursiveKsort($value);
            }
        }
    }
}
