<?php

namespace App\Infrastructure\Persistence;

use App\Application\DTO\DeviceEventEnvelope;
use App\Entity\Device;
use App\Entity\DeviceEvent;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Uid\Uuid;

class RawDeviceEventRecorder
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * Records a raw device event durably.
     *
     * @param DeviceEventEnvelope $envelope The validated ingestion envelope
     * @param Device|null $device The resolved device entity if known
     * @return DeviceEvent The recorded event entity
     */
    public function recordEvent(
        DeviceEventEnvelope $envelope,
        ?Device $device = null
    ): DeviceEvent {
        $event = new DeviceEvent();
        
        // Generate UUID
        $event->setEventUuid(Uuid::v4()->toRfc4122());
        
        // Set metadata
        $event->setSourceType($envelope->getSourceType());
        $event->setSourceIp($envelope->getSourceIp());
        $event->setDevice($device);
        $event->setDeviceTimestamp($envelope->getDeviceTimestamp());
        
        // Microsecond precision receive timestamp is generated by default in constructor, 
        // but we can ensure it here.
        $event->setReceivedAt(new \DateTimeImmutable());
        
        $payload = $envelope->getRawPayload();
        
        // Hash and store payload
        $event->setRawPayload($payload);
        
        // Sort keys recursively for consistent hashing, encode without pretty print
        $this->recursiveKsort($payload);
        $jsonString = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        $event->setPayloadHash(hash('sha256', $jsonString));
        
        // Processing status defaults to 'received', attempts to 0

        // Persist using transaction
        $this->entityManager->wrapInTransaction(function () use ($event) {
            $this->entityManager->persist($event);
            $this->entityManager->flush();
        });

        return $event;
    }

    private function recursiveKsort(array &$array): void
    {
        ksort($array);
        foreach ($array as &$value) {
            if (is_array($value)) {
                $this->recursiveKsort($value);
            }
        }
    }
}
